# Generated by Django 4.1.2 on 2022-10-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Primer_MVT', '0002_familiar_fecha_nacimiento_alter_familiar_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(default='', max_length=300)),
                ('titulo', models.CharField(default='', max_length=40)),
                ('autor', models.CharField(default='', max_length=100)),
                ('fecha', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
