# Generated by Django 4.1.2 on 2022-10-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Primer_MVT', '0003_categoria_posteo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiar',
            new_name='Usuario',
        ),
        migrations.AlterField(
            model_name='posteo',
            name='fecha',
            field=models.CharField(default='', max_length=20),
        ),
    ]
