# Generated by Django 4.1.2 on 2022-11-20 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Primer_MVT', '0004_rename_familiar_usuario_alter_posteo_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='autor',
        ),
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/posteos'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 4, 18, 44, 911246, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='mensaje',
            field=models.TextField(default='', max_length=300),
        ),
    ]
