# Generated by Django 4.1.2 on 2022-11-23 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Primer_MVT', '0006_delete_categoria_remove_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
